# Generated by Django 5.2.7 on 2025-10-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_alter_form_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
